/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author PHT
 */
public class FontDialog extends javax.swing.JDialog {

    /**
     * Creates new form Font
     *
     * @param parent
     * @param modal
     */
    public FontDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JLabel getTxtSample() {
        return txtSample;
    }

    public void setTxtSample(JLabel txtSample) {
        this.txtSample = txtSample;
    }

    public JButton getjButtonCancel() {
        return jButtonCancel;
    }

    public void setjButtonCancel(JButton jButtonCancel) {
        this.jButtonCancel = jButtonCancel;
    }

    public JButton getjButtonOk() {
        return jButtonOk;
    }

    public void setjButtonOk(JButton jButtonOk) {
        this.jButtonOk = jButtonOk;
    }

    public JLabel getjLabelFont() {
        return jLabelFont;
    }

    public void setjLabelFont(JLabel jLabelFont) {
        this.jLabelFont = jLabelFont;
    }

    public JLabel getjLabelFontStyle() {
        return jLabelFontStyle;
    }

    public void setjLabelFontStyle(JLabel jLabelFontStyle) {
        this.jLabelFontStyle = jLabelFontStyle;
    }

    public JLabel getjLabelSize() {
        return jLabelSize;
    }

    public void setjLabelSize(JLabel jLabelSize) {
        this.jLabelSize = jLabelSize;
    }

    public JList<String> getjListFont() {
        return jListFont;
    }

    public void setjListFont(JList<String> jListFont) {
        this.jListFont = jListFont;
    }

    public JList<String> getjListFontStyle() {
        return jListFontStyle;
    }

    public void setjListFontStyle(JList<String> jListFontStyle) {
        this.jListFontStyle = jListFontStyle;
    }

    public JList getjListSize() {
        return jListSize;
    }

    public void setjListSize(JList jListSize) {
        this.jListSize = jListSize;
    }

    public JPanel getjPanelSample() {
        return jPanelSample;
    }

    public void setjPanelSample(JPanel jPanelSample) {
        this.jPanelSample = jPanelSample;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPaneSize() {
        return jScrollPaneSize;
    }

    public void setjScrollPaneSize(JScrollPane jScrollPaneSize) {
        this.jScrollPaneSize = jScrollPaneSize;
    }

    public JTextField getjTextFieldFont() {
        return jTextFieldFont;
    }

    public void setjTextFieldFont(JTextField jTextFieldFont) {
        this.jTextFieldFont = jTextFieldFont;
    }

    public JTextField getjTextFieldFontStyle() {
        return jTextFieldFontStyle;
    }

    public void setjTextFieldFontStyle(JTextField jTextFieldFontStyle) {
        this.jTextFieldFontStyle = jTextFieldFontStyle;
    }

    public JTextField getjTextFieldSize() {
        return jTextFieldSize;
    }

    public void setjTextFieldSize(JTextField jTextFieldSize) {
        this.jTextFieldSize = jTextFieldSize;
    }

    public JLabel getLbPreview() {
        return lbPreview;
    }

    public void setLbPreview(JLabel lbPreview) {
        this.lbPreview = lbPreview;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldFontStyle = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListFontStyle = new javax.swing.JList<>();
        jLabelSize = new javax.swing.JLabel();
        jTextFieldSize = new javax.swing.JTextField();
        jLabelFont = new javax.swing.JLabel();
        jTextFieldFont = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFont = new javax.swing.JList<>();
        jScrollPaneSize = new javax.swing.JScrollPane();
        jListSize = new javax.swing.JList();
        jLabelFontStyle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelSample = new javax.swing.JPanel();
        lbPreview = new javax.swing.JLabel();
        txtSample = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setViewportView(jListFontStyle);

        jLabelSize.setDisplayedMnemonic('s');
        jLabelSize.setText("Size:");

        jLabelFont.setDisplayedMnemonic('f');
        jLabelFont.setText("Font:");
        jLabelFont.setToolTipText("");

        jScrollPane1.setViewportView(jListFont);

        jScrollPaneSize.setViewportView(jListSize);

        jLabelFontStyle.setDisplayedMnemonic('y');
        jLabelFontStyle.setText("Font Style:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldFont, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFont, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFontStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFontStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPaneSize, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFont)
                    .addComponent(jLabelFontStyle)
                    .addComponent(jLabelSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFontStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPaneSize)))
        );

        jPanelSample.setBorder(javax.swing.BorderFactory.createTitledBorder("Sample"));
        jPanelSample.setPreferredSize(new java.awt.Dimension(200, 80));

        txtSample.setText("AaBbCc");

        javax.swing.GroupLayout jPanelSampleLayout = new javax.swing.GroupLayout(jPanelSample);
        jPanelSample.setLayout(jPanelSampleLayout);
        jPanelSampleLayout.setHorizontalGroup(
            jPanelSampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSampleLayout.createSequentialGroup()
                .addGroup(jPanelSampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSampleLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbPreview))
                    .addGroup(jPanelSampleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSample)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanelSampleLayout.setVerticalGroup(
            jPanelSampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSampleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSample)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 227, Short.MAX_VALUE)
                .addComponent(jPanelSample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelSample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        jPanelSample.getAccessibleContext().setAccessibleName("Preview");

        jButtonOk.setText("OK");

        jButtonCancel.setText("Cancel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelFont;
    private javax.swing.JLabel jLabelFontStyle;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JList<String> jListFont;
    private javax.swing.JList<String> jListFontStyle;
    private javax.swing.JList jListSize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSample;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneSize;
    private javax.swing.JTextField jTextFieldFont;
    private javax.swing.JTextField jTextFieldFontStyle;
    private javax.swing.JTextField jTextFieldSize;
    private javax.swing.JLabel lbPreview;
    private javax.swing.JLabel txtSample;
    // End of variables declaration//GEN-END:variables
}
