/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 *
 * @author PHT
 */
public class ReplaceDialog extends javax.swing.JDialog {

    /**
     * Creates new form ReplaceDialog
     */
    public ReplaceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JButton getjButtonCancel() {
        return jButtonCancel;
    }

    public void setjButtonCancel(JButton jButtonCancel) {
        this.jButtonCancel = jButtonCancel;
    }

    public JButton getjButtonFindNext() {
        return jButtonFindNext;
    }

    public void setjButtonFindNext(JButton jButtonFindNext) {
        this.jButtonFindNext = jButtonFindNext;
    }

    public JButton getjButtonReplace() {
        return jButtonReplace;
    }

    public void setjButtonReplace(JButton jButtonReplace) {
        this.jButtonReplace = jButtonReplace;
    }

    public JButton getjButtonReplaceAll() {
        return jButtonReplaceAll;
    }

    public void setjButtonReplaceAll(JButton jButtonReplaceAll) {
        this.jButtonReplaceAll = jButtonReplaceAll;
    }

    public JLabel getjLabelFind() {
        return jLabelFind;
    }

    public void setjLabelFind(JLabel jLabelFind) {
        this.jLabelFind = jLabelFind;
    }

    public JLabel getjLabelReplace() {
        return jLabelReplace;
    }

    public void setjLabelReplace(JLabel jLabelReplace) {
        this.jLabelReplace = jLabelReplace;
    }

    public JTextField getjTextFieldFind() {
        return jTextFieldFind;
    }

    public void setjTextFieldFind(JTextField jTextFieldFind) {
        this.jTextFieldFind = jTextFieldFind;
    }

    public JTextField getjTextFieldReplace() {
        return jTextFieldReplace;
    }

    public void setjTextFieldReplace(JTextField jTextFieldReplace) {
        this.jTextFieldReplace = jTextFieldReplace;
    }

    public JCheckBox getCheckAround() {
        return checkAround;
    }

    public void setCheckAround(JCheckBox checkAround) {
        this.checkAround = checkAround;
    }

    public JCheckBox getCheckCase() {
        return checkCase;
    }

    public void setCheckCase(JCheckBox checkCase) {
        this.checkCase = checkCase;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFind = new javax.swing.JLabel();
        jTextFieldFind = new javax.swing.JTextField();
        jLabelReplace = new javax.swing.JLabel();
        jTextFieldReplace = new javax.swing.JTextField();
        jButtonFindNext = new javax.swing.JButton();
        jButtonReplace = new javax.swing.JButton();
        jButtonReplaceAll = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        checkCase = new javax.swing.JCheckBox();
        checkAround = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelFind.setDisplayedMnemonic('n');
        jLabelFind.setText("Find what:");

        jLabelReplace.setDisplayedMnemonic('p');
        jLabelReplace.setText("Replace with:");

        jButtonFindNext.setMnemonic('f');
        jButtonFindNext.setText("Find Next");

        jButtonReplace.setMnemonic('r');
        jButtonReplace.setText("Replace");

        jButtonReplaceAll.setMnemonic('a');
        jButtonReplaceAll.setText("Replace All");

        jButtonCancel.setText("Cancel");

        checkCase.setText("Macth Case");

        checkAround.setText("Wrap around");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFind, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelReplace))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldFind, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jTextFieldReplace)))
                    .addComponent(checkAround)
                    .addComponent(checkCase))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFindNext, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReplaceAll, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFind, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFindNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonReplace))
                    .addComponent(jLabelReplace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReplaceAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addGap(1, 1, 1)
                .addComponent(checkCase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkAround)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkAround;
    private javax.swing.JCheckBox checkCase;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonFindNext;
    private javax.swing.JButton jButtonReplace;
    private javax.swing.JButton jButtonReplaceAll;
    private javax.swing.JLabel jLabelFind;
    private javax.swing.JLabel jLabelReplace;
    private javax.swing.JTextField jTextFieldFind;
    private javax.swing.JTextField jTextFieldReplace;
    // End of variables declaration//GEN-END:variables
}
