/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.TextArea;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTextArea;

/**
 *
 * @author PHT
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    public JTextArea getTxtOutPut() {
        return txtOutPut;
    }

    public void setTxtOutPut(JTextArea txtOutPut) {
        this.txtOutPut = txtOutPut;
    }



    public JMenuItem getfExit() {
        return fExit;
    }

    public void setfExit(JMenuItem fExit) {
        this.fExit = fExit;
    }

    public JMenuItem getfNew() {
        return fNew;
    }

    public void setfNew(JMenuItem fNew) {
        this.fNew = fNew;
    }

    public JMenuItem getfOpen() {
        return fOpen;
    }

    public void setfOpen(JMenuItem fOpen) {
        this.fOpen = fOpen;
    }

    public JMenuItem getfSave() {
        return fSave;
    }

    public void setfSave(JMenuItem fSave) {
        this.fSave = fSave;
    }

    public JMenuItem getfSaveAs() {
        return fSaveAs;
    }

    public void setfSaveAs(JMenuItem fSaveAs) {
        this.fSaveAs = fSaveAs;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JPopupMenu.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JPopupMenu.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JPopupMenu.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JPopupMenu.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JPopupMenu.Separator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JPopupMenu.Separator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    public JPopupMenu.Separator getjSeparator5() {
        return jSeparator5;
    }

    public void setjSeparator5(JPopupMenu.Separator jSeparator5) {
        this.jSeparator5 = jSeparator5;
    }

    public JMenuItem getsChangeFont() {
        return sChangeFont;
    }

    public void setsChangeFont(JMenuItem sChangeFont) {
        this.sChangeFont = sChangeFont;
    }

    public JMenuItem getsCopy() {
        return sCopy;
    }

    public void setsCopy(JMenuItem sCopy) {
        this.sCopy = sCopy;
    }

    public JMenuItem getsCut() {
        return sCut;
    }

    public void setsCut(JMenuItem sCut) {
        this.sCut = sCut;
    }

    public JMenuItem getsDelete() {
        return sDelete;
    }

    public void setsDelete(JMenuItem sDelete) {
        this.sDelete = sDelete;
    }

    public JMenuItem getsFind() {
        return sFind;
    }

    public void setsFind(JMenuItem sFind) {
        this.sFind = sFind;
    }

    public JMenuItem getsPaste() {
        return sPaste;
    }

    public void setsPaste(JMenuItem sPaste) {
        this.sPaste = sPaste;
    }

    public JMenuItem getsRedo() {
        return sRedo;
    }

    public void setsRedo(JMenuItem sRedo) {
        this.sRedo = sRedo;
    }

    public JMenuItem getsReplace() {
        return sReplace;
    }

    public void setsReplace(JMenuItem sReplace) {
        this.sReplace = sReplace;
    }

    public JMenuItem getsSelectAll() {
        return sSelectAll;
    }

    public void setsSelectAll(JMenuItem sSelectAll) {
        this.sSelectAll = sSelectAll;
    }

    public JMenuItem getsUndo() {
        return sUndo;
    }

    public void setsUndo(JMenuItem sUndo) {
        this.sUndo = sUndo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutPut = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        fNew = new javax.swing.JMenuItem();
        fOpen = new javax.swing.JMenuItem();
        fSave = new javax.swing.JMenuItem();
        fSaveAs = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        fExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        sUndo = new javax.swing.JMenuItem();
        sRedo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sCut = new javax.swing.JMenuItem();
        sCopy = new javax.swing.JMenuItem();
        sPaste = new javax.swing.JMenuItem();
        sDelete = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        sFind = new javax.swing.JMenuItem();
        sReplace = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        sSelectAll = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        sChangeFont = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Text Editor (MTE)");

        txtOutPut.setColumns(20);
        txtOutPut.setRows(5);
        jScrollPane1.setViewportView(txtOutPut);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N

        fNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        fNew.setText("New");
        jMenu1.add(fNew);

        fOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        fOpen.setText("Open");
        fOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fOpenActionPerformed(evt);
            }
        });
        jMenu1.add(fOpen);

        fSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        fSave.setText("Save");
        jMenu1.add(fSave);

        fSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        fSaveAs.setText("Save as");
        jMenu1.add(fSaveAs);
        jMenu1.add(jSeparator2);

        fExit.setText("Exit");
        jMenu1.add(fExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N

        sUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        sUndo.setText("Undo");
        jMenu2.add(sUndo);

        sRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        sRedo.setText("Redo");
        jMenu2.add(sRedo);
        jMenu2.add(jSeparator1);

        sCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        sCut.setText("Cut");
        jMenu2.add(sCut);

        sCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        sCopy.setText("Copy");
        sCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCopyActionPerformed(evt);
            }
        });
        jMenu2.add(sCopy);

        sPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        sPaste.setText("Paste");
        jMenu2.add(sPaste);

        sDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        sDelete.setText("Delete");
        jMenu2.add(sDelete);
        jMenu2.add(jSeparator3);

        sFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        sFind.setText("Find");
        jMenu2.add(sFind);

        sReplace.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        sReplace.setText("Replace");
        jMenu2.add(sReplace);
        jMenu2.add(jSeparator4);

        sSelectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        sSelectAll.setText("Select all");
        jMenu2.add(sSelectAll);
        jMenu2.add(jSeparator5);

        sChangeFont.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sChangeFont.setText("Change font");
        jMenu2.add(sChangeFont);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCopyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sCopyActionPerformed

    private void fOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fOpenActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem fExit;
    private javax.swing.JMenuItem fNew;
    private javax.swing.JMenuItem fOpen;
    private javax.swing.JMenuItem fSave;
    private javax.swing.JMenuItem fSaveAs;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem sChangeFont;
    private javax.swing.JMenuItem sCopy;
    private javax.swing.JMenuItem sCut;
    private javax.swing.JMenuItem sDelete;
    private javax.swing.JMenuItem sFind;
    private javax.swing.JMenuItem sPaste;
    private javax.swing.JMenuItem sRedo;
    private javax.swing.JMenuItem sReplace;
    private javax.swing.JMenuItem sSelectAll;
    private javax.swing.JMenuItem sUndo;
    private javax.swing.JTextArea txtOutPut;
    // End of variables declaration//GEN-END:variables
}
